#!/usr/bin/env python3
"""Activate .github/CODEOWNERS (and optionally LICENSE) and keep the audit
ledger and manifest consistent.

Copying .github/CODEOWNERS.example by hand fails the release gate, because
docs/audit/FILE_REVIEW_LEDGER.csv enforces an exact path set and
RELEASE_MANIFEST.json enforces an exact file set with hashes. This script
performs every required step in the one order that works:

  1. write .github/CODEOWNERS with the real owner substituted;
  2. optionally write LICENSE from LICENSE.example with the legal owner;
  3. insert the matching file-review ledger rows;
  4. rebuild docs/audit/FUNCTION_PARITY_MATRIX.csv;
  5. rebuild RELEASE_MANIFEST.json and RELEASE_SHA256.txt;
  6. verify both ledgers and the manifest.

Step 4 must precede step 5, because the function-parity matrix is itself a
manifested file.

Usage:
    python scripts/activate_codeowners.py --owner @your-github-username
    python scripts/activate_codeowners.py --owner @you --license-owner "Jane Doe"

The owner may be a user (@name) or a team (@org/team). Re-running with a
different owner rewrites the files without duplicating ledger rows.
"""

from __future__ import annotations

import argparse
import csv
import re
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
EXAMPLE = ROOT / ".github/CODEOWNERS.example"
TARGET = ROOT / ".github/CODEOWNERS"
LICENSE_EXAMPLE = ROOT / "LICENSE.example"
LICENSE_TARGET = ROOT / "LICENSE"
LEDGER = ROOT / "docs/audit/FILE_REVIEW_LEDGER.csv"
LEDGER_FIELDS = ["path", "category", "review_scope", "disposition", "notable_result"]
PLACEHOLDER = "@YOUR_GITHUB_USERNAME"
LICENSE_PLACEHOLDER = "<LICENSE_OWNER>"

# The instructional header of CODEOWNERS.example describes how to generate the
# real file. It must be rewritten BEFORE the owner substitution runs, otherwise
# the placeholder inside it has already been replaced and the generated file
# tells the reader to "replace @real-owner with the real repository owner".
EXAMPLE_HEADER = (
    "# Copy this file to .github/CODEOWNERS, replace @YOUR_GITHUB_USERNAME with the\n"
    "# real repository owner, and enable branch protection\n"
)
GENERATED_HEADER = (
    "# Generated by scripts/activate_codeowners.py. Do not edit by hand: the\n"
    "# file-review ledger and RELEASE_MANIFEST.json pin its exact bytes.\n"
    "# Enable branch protection\n"
)

LEDGER_ROWS = {
    ".github/CODEOWNERS": {
        "path": ".github/CODEOWNERS",
        "category": "GitHub",
        "review_scope": "Active code-owner policy",
        "disposition": "REVIEWED",
        "notable_result": (
            "Activated from the shipped example with the real repository owner; requires "
            "code-owner review for strategy, live-gate, pair-policy, manifest, workflow "
            "and deployment paths. Branch protection must require Code Owner review."
        ),
    },
    "LICENSE": {
        "path": "LICENSE",
        "category": "Legal",
        "review_scope": "Copyright grant, warranty and liability disclaimers, trading-risk notice",
        "disposition": "REVIEWED",
        "notable_result": (
            "Activated from LICENSE.example with the real legal owner. All rights "
            "reserved; no use, copy, modify or distribution right is granted. States "
            "that the package is not certified for real-money trading. Baseline "
            "wording only; requires professional legal review."
        ),
    },
}

OWNER_PATTERN = re.compile(r"^@[A-Za-z0-9][A-Za-z0-9-]{0,38}(/[A-Za-z0-9._-]{1,100})?$")
OWNER_LINE = re.compile(r"^\s*/\S+\s+@\S+")

REJECTED_LICENSE_OWNERS = {
    "",
    "your full legal name",
    "your full legal name or company ltd",
    "your name",
    "owner_name",
    "license_owner",
    "<license_owner>",
    "changeme",
    "todo",
}


def validate_owner(owner: str) -> str:
    owner = owner.strip()
    if not owner.startswith("@"):
        owner = "@" + owner
    if not OWNER_PATTERN.match(owner):
        raise SystemExit(
            f"invalid code owner {owner!r}; expected @username or @org/team"
        )
    if owner == PLACEHOLDER:
        raise SystemExit("refusing to activate CODEOWNERS with the shipped placeholder")
    return owner


def validate_license_owner(owner: str) -> str:
    owner = " ".join(owner.split())
    if owner.lower() in REJECTED_LICENSE_OWNERS:
        raise SystemExit(
            f"refusing to write LICENSE with the placeholder owner {owner!r}"
        )
    if len(owner) < 2:
        raise SystemExit("licence owner must be a real legal name")
    if LICENSE_PLACEHOLDER in owner:
        raise SystemExit("refusing to write LICENSE with the shipped placeholder")
    return owner


def write_codeowners(owner: str) -> int:
    if not EXAMPLE.is_file():
        raise SystemExit(f"missing template: {EXAMPLE}")
    text = EXAMPLE.read_text(encoding="utf-8")
    if PLACEHOLDER not in text:
        raise SystemExit(f"template contains no {PLACEHOLDER} placeholder")

    # Rewrite the instructional header first, while the placeholder it mentions
    # is still literally present.
    if EXAMPLE_HEADER in text:
        body = text.replace(EXAMPLE_HEADER, GENERATED_HEADER)
    else:
        body = text
    body = body.replace(PLACEHOLDER, owner)

    if PLACEHOLDER in body:
        raise SystemExit("internal error: placeholder survived substitution")

    # Count real ownership rules, not comment mentions.
    entries = sum(1 for line in body.splitlines() if OWNER_LINE.match(line))
    if entries == 0:
        raise SystemExit("generated CODEOWNERS contains no ownership rules")

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    _atomic_write(TARGET, body)
    return entries


def write_license(license_owner: str) -> None:
    if not LICENSE_EXAMPLE.is_file():
        raise SystemExit(f"missing template: {LICENSE_EXAMPLE}")
    text = LICENSE_EXAMPLE.read_text(encoding="utf-8")
    if LICENSE_PLACEHOLDER not in text:
        raise SystemExit(f"template contains no {LICENSE_PLACEHOLDER} placeholder")
    body = text.replace(LICENSE_PLACEHOLDER, license_owner)
    # Drop the activation instructions from the real licence file.
    marker = "-" * 79 + "\nHOW TO ACTIVATE THIS LICENCE"
    if marker in body:
        body = body.split(marker, 1)[0].rstrip() + "\n"
    if LICENSE_PLACEHOLDER in body:
        raise SystemExit("internal error: licence placeholder survived substitution")
    _atomic_write(LICENSE_TARGET, body)


def _atomic_write(target: Path, body: str) -> None:
    """Write via a temporary file in the same directory, then replace."""
    temporary = target.with_name(target.name + ".tmp")
    try:
        temporary.write_text(body, encoding="utf-8", newline="\n")
        temporary.replace(target)
    finally:
        if temporary.exists():
            temporary.unlink()


def ensure_ledger_rows(paths: list[str]) -> list[str]:
    with LEDGER.open(encoding="utf-8", newline="") as handle:
        rows = list(csv.DictReader(handle))
    present = {row["path"] for row in rows}
    added = [path for path in paths if path not in present]
    if not added:
        return []
    for path in added:
        rows.append(dict(LEDGER_ROWS[path]))
    rows.sort(key=lambda row: row["path"])
    # csv.DictWriter defaults to '\r\n'. The ledger is a manifested file whose
    # exact bytes are pinned by RELEASE_MANIFEST.json and normalised to LF by
    # .gitattributes, so the terminator must be forced to '\n' -- otherwise
    # activation silently rewrites every line and fails verify_manifest.py.
    with LEDGER.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=LEDGER_FIELDS,
            quoting=csv.QUOTE_ALL,
            lineterminator="\n",
        )
        writer.writeheader()
        writer.writerows(rows)
    return added


def run(script: str, *arguments: str) -> None:
    subprocess.run(
        [sys.executable, str(ROOT / "scripts" / script), *arguments],
        cwd=ROOT,
        check=True,
    )


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Activate CODEOWNERS and optionally LICENSE, then rebuild "
        "the audit ledgers and release manifest."
    )
    parser.add_argument(
        "--owner",
        required=True,
        help="GitHub code owner, for example @your-github-username or @org/team",
    )
    parser.add_argument(
        "--license-owner",
        default=None,
        help="Legal copyright owner. When given, writes LICENSE from "
        "LICENSE.example. Omit to leave licensing untouched.",
    )
    args = parser.parse_args()

    owner = validate_owner(args.owner)
    license_owner = (
        validate_license_owner(args.license_owner) if args.license_owner else None
    )

    entries = write_codeowners(owner)
    activated = [".github/CODEOWNERS"]
    if license_owner:
        write_license(license_owner)
        activated.append("LICENSE")

    added = ensure_ledger_rows(activated)

    try:
        # Order matters: the function-parity matrix is itself manifested, so it
        # must be regenerated before the manifest is built.
        run("build_audit_ledgers.py")
        run("build_manifest.py")
        run("verify_manifest.py")
        run("build_audit_ledgers.py", "--check")
    except subprocess.CalledProcessError as exc:
        print(
            "activation failed during verification; "
            "inspect the tree before committing",
            file=sys.stderr,
        )
        return exc.returncode or 1

    print(f"wrote .github/CODEOWNERS with {entries} ownership rules -> {owner}")
    if license_owner:
        print(f"wrote LICENSE -> {license_owner} (proprietary, all rights reserved)")
    print(
        "file-review ledger rows "
        + (f"added: {', '.join(added)}" if added else "already present")
    )
    print("audit ledgers and manifest rebuilt and verified")
    print("next: run 'bash deploy/verify_release.sh' before committing")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
