#!/usr/bin/env python3
from __future__ import annotations
"""Offline Ed25519 certifier for the live-promotion evidence gate.

The private key generated by this script must never be copied to Oracle,
GitHub, the release ZIP, or a trading container.
"""

import argparse
import json
import os
from pathlib import Path
import shutil
import sys
import time


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


RISK_ENV_NAMES = {
    "BTC_QUOTE_ALLOWLIST", "ALLOWED_STABLE_QUOTES", "TRADE_SIZE_QUOTE",
    "TAKE_PROFIT_PCT",
    "FIXED_STOP_PCT", "TRAILING_DELTA_BIPS", "LIMIT_FILL_BUFFER_BIPS",
    "FEE_PCT_PER_SIDE", "BREAK_EVEN_SLIPPAGE_PCT", "SPOT_FILTER_MAX_AGE_SECONDS",
    "AUTO_PROTECTION_ENABLED", "MONEYFLOW_REFRESH_SECONDS",
    "MONEYFLOW_DEPTH_LIMIT", "MONEYFLOW_TRADE_LIMIT", "MONEYFLOW_DEPTH_BAND_BPS",
    "AUTO_BREAK_EVEN_TRIGGER_PCT", "AUTO_TIGHT_TRAIL_BIPS",
    "MAX_SIGNAL_AGE_SECONDS", "MAX_CANDLE_AGE_SECONDS",
    "PAIR_COOLDOWN_SECONDS", "MAX_STOPOUTS_PER_PAIR_DAY",
    "MAX_STOPOUTS_GLOBAL_DAY", "REQUIRE_FLOW_CONTEXT",
    "REQUIRE_MATCHING_FUTURES", "MAX_FLOW_AGE_SECONDS",
    "FLOW_MIN_TAKER_BUY_RATIO", "FLOW_MIN_SPOT_IMBALANCE",
    "LIVE_MIN_BACKTEST_TRADES", "LIVE_MIN_PROFIT_FACTOR",
    "LIVE_MIN_PROFIT_TOTAL", "LIVE_MAX_DRAWDOWN_ACCOUNT",
    "LIVE_MIN_BACKTEST_FEE",
}


def _load_risk_env(path: Path | None) -> None:
    if path is None:
        return
    for number, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            raise SystemExit(f"{path}:{number}: expected NAME=value")
        name, value = line.split("=", 1)
        name = name.strip()
        if name in RISK_ENV_NAMES:
            os.environ[name] = value.strip().strip('"').strip("'")


def _keygen(args) -> None:
    from Crypto.PublicKey import ECC
    from services.common.evidence_signature import public_key_b64

    private_path, public_path = Path(args.private_key), Path(args.public_env)
    if private_path.exists() or public_path.exists():
        raise SystemExit("refusing to overwrite an existing key or public-env file")
    private_path.parent.mkdir(parents=True, exist_ok=True)
    public_path.parent.mkdir(parents=True, exist_ok=True)
    key = ECC.generate(curve="Ed25519")
    private_path.write_text(key.export_key(format="PEM") + "\n", encoding="utf-8")
    try:
        os.chmod(private_path, 0o600)
    except OSError:
        pass
    public_path.write_text(
        "LIVE_EVIDENCE_PUBLIC_KEY=" + public_key_b64(key) + "\n", encoding="utf-8")
    print(f"private key created: {private_path} (KEEP OFFLINE; NEVER DEPLOY)")
    print(f"public environment line created: {public_path}")


def _template(args) -> None:
    from services.execution_sidecar.live_evidence import REQUIRED_ASSERTIONS

    target = Path(args.output)
    if target.exists():
        raise SystemExit("refusing to overwrite an existing assertions file")
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps({name: False for name in REQUIRED_ASSERTIONS},
                                 indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"assertion checklist created: {target}; set true only from retained evidence")


def _certify(args) -> None:
    _load_risk_env(Path(args.risk_env) if args.risk_env else None)
    output_dir = Path(args.output_dir).resolve()
    os.environ["RUNTIME_DIR"] = str(output_dir)

    from Crypto.PublicKey import ECC
    from services.common.evidence_signature import public_key_b64, sign_document
    from services.common.market_policy import allowed_quotes_from_env, pair_state_hash
    from services.execution_sidecar.live_evidence import (
        EVIDENCE_PRODUCER, REQUIRED_ASSERTIONS, risk_policy_sha256,
        verified_backtest, verify_live_evidence,
    )

    release_root = Path(args.release_root).resolve()
    release_hash = (release_root / "RELEASE_SHA256.txt").read_text(
        encoding="utf-8").split()[0]
    manifest = json.loads((release_root / "RELEASE_MANIFEST.json").read_text(encoding="utf-8"))
    fingerprints = manifest.get("preservation", {}).get("strategy_signal_fingerprints")
    if not isinstance(fingerprints, dict) or not fingerprints:
        raise SystemExit("release manifest lacks strategy fingerprints")
    strategy_sha256 = (manifest.get("files", {}).get(
        "freqtrade/user_data/strategies/IctSmcStrategy.py", {}).get("sha256"))
    if not isinstance(strategy_sha256, str) or len(strategy_sha256) != 64:
        raise SystemExit("release manifest lacks the full strategy file hash")
    active_pair = json.loads(Path(args.active_pair).read_text(encoding="utf-8"))
    assertions = json.loads(Path(args.assertions).read_text(encoding="utf-8"))
    missing = [name for name in REQUIRED_ASSERTIONS if assertions.get(name) is not True]
    if missing:
        raise SystemExit("refusing to certify; unmet assertions: " + ", ".join(missing))

    key = ECC.import_key(Path(args.private_key).read_text(encoding="utf-8"))
    if not key.has_private() or key.curve != "Ed25519":
        raise SystemExit("private key is not an Ed25519 private key")
    quotes = allowed_quotes_from_env()
    output_dir.mkdir(parents=True, exist_ok=True)
    backtest_dir = output_dir / "backtests"
    backtest_dir.mkdir(parents=True, exist_ok=True)
    source = Path(args.backtest).resolve()
    import hashlib
    digest = hashlib.sha256(source.read_bytes()).hexdigest()
    suffix = ".zip" if source.suffix.lower() == ".zip" else ".json"
    artifact_name = f"IctSmcStrategy-{digest}{suffix}"
    destination = backtest_dir / artifact_name
    if destination.exists() and hashlib.sha256(destination.read_bytes()).hexdigest() != digest:
        raise SystemExit("existing backtest destination has unexpected bytes")
    if not destination.exists():
        shutil.copyfile(source, destination)
    backtest = {"artifact_file": artifact_name, "artifact_sha256": digest}
    metrics = verified_backtest(
        backtest, active_pair_state=active_pair, allowed_quotes=quotes,
        strategy_fingerprints=fingerprints, strategy_file_sha256=strategy_sha256)
    payload = {
        "release_hash": release_hash,
        "strategy_fingerprints": fingerprints,
        "strategy_file_sha256": strategy_sha256,
        "active_pair_state_hash": pair_state_hash(active_pair),
        "allowed_stable_quotes": sorted(quotes),
        "risk_policy_sha256": risk_policy_sha256(quotes),
        "freqtrade_backtest": backtest,
        "verified_backtest_metrics": metrics,
        "assertions": {name: True for name in REQUIRED_ASSERTIONS},
        "certifier_note": str(args.note or "")[:500],
    }
    document = sign_document(
        payload=payload, private_key=key, producer=EVIDENCE_PRODUCER,
        valid_seconds=int(args.valid_days) * 86400)
    target = output_dir / f"LIVE_EVIDENCE.{release_hash}.json"
    temporary = target.with_name(target.name + f".{os.getpid()}.tmp")
    temporary.write_text(json.dumps(document, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    try:
        os.chmod(temporary, 0o640)
    except OSError:
        pass
    os.replace(temporary, target)

    # Re-run the runtime verifier against the exact emitted bytes and public key.
    os.environ["LIVE_EVIDENCE_PUBLIC_KEY"] = public_key_b64(key)
    verify_live_evidence(
        release_hash=release_hash, strategy_fingerprints=fingerprints,
        strategy_file_sha256=strategy_sha256,
        active_pair_state=active_pair, allowed_quotes=quotes, path=target)
    print(f"certified evidence: {target}")
    print(f"backtest artifact: {destination}")
    print("public key (safe to deploy): LIVE_EVIDENCE_PUBLIC_KEY=" + public_key_b64(key))
    print("private key was read only; it was not copied to the output directory")


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest="command", required=True)
    keygen = commands.add_parser("keygen", help="generate an offline Ed25519 keypair")
    keygen.add_argument("--private-key", required=True)
    keygen.add_argument("--public-env", required=True)
    keygen.set_defaults(func=_keygen)
    template = commands.add_parser("template", help="create a fail-closed assertion checklist")
    template.add_argument("--output", required=True)
    template.set_defaults(func=_template)
    certify = commands.add_parser("certify", help="validate and sign one exact release promotion")
    certify.add_argument("--private-key", required=True)
    certify.add_argument("--release-root", default=str(ROOT))
    certify.add_argument("--active-pair", required=True)
    certify.add_argument("--backtest", required=True)
    certify.add_argument("--assertions", required=True)
    certify.add_argument("--risk-env", help="deployment .env; only non-secret risk fields are loaded")
    certify.add_argument("--output-dir", required=True)
    certify.add_argument("--valid-days", type=int, default=30, choices=range(1, 91))
    certify.add_argument("--note", default="")
    certify.set_defaults(func=_certify)
    return parser


def main() -> None:
    args = _parser().parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
